### ISSUE TITLE
infografia

### ISSUE THREAD

**Issue by PedroGarcia11439** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-PedroGarcia11439#1]
[Infografia_Pedro Garcia.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-PedroGarcia11439/files/14566946/Infografia_Pedro.Garcia.pdf)

**Comment by josealfredo79** [comment]
@PedroGarcia11439 Falta la calificación...

**Comment by josealfredo79** [comment]
Calificacion 18
